In [1]:
import numpy as np

In [2]:
a=np.array([1,2,3])

In [3]:
a

array([1, 2, 3])

In [4]:
b=np.array([(1.5,2,3),(4,5,6)],dtype=float)

In [5]:
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [6]:
c=np.array([[(1.5,2,3),(4,5,6)],[(3,2,1),(4,5,6)]],dtype=float)

In [7]:
c

array([[[1.5, 2. , 3. ],
        [4. , 5. , 6. ]],

       [[3. , 2. , 1. ],
        [4. , 5. , 6. ]]])

In [8]:
np.zeros((3,7))

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [9]:
np.ones((2,3,5),dtype=int)

array([[[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]])

In [10]:
np.arange(10,25,5)

array([10, 15, 20])

In [11]:
e=np.linspace(0,2,9)

In [12]:
e

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [13]:
np.full((2,2),9)

array([[9, 9],
       [9, 9]])

In [14]:
x=np.eye(2)
y=np.random.random((2,2))

In [15]:
x

array([[1., 0.],
       [0., 1.]])

In [16]:
y

array([[0.84956731, 0.39921489],
       [0.18153044, 0.89750242]])

In [17]:
np.shape(a)

(3,)

In [18]:
np.shape(b)

(2, 3)

In [19]:
np.shape(c)

(2, 2, 3)

In [20]:
np.ndim(a)

1

In [21]:
np.ndim(b)

2

In [22]:
np.ndim(c)

3

In [23]:
np.size(a)

3

In [24]:
np.size(b)

6

In [25]:
np.size(c)

12

In [26]:
a.dtype

dtype('int32')

In [27]:
b.dtype

dtype('float64')

In [28]:
c.dtype

dtype('float64')

In [29]:
a.dtype.name

'int32'

In [30]:
b.dtype.name

'float64'

In [31]:
c.dtype.name

'float64'

In [32]:
b.astype(int)

array([[1, 2, 3],
       [4, 5, 6]])

In [33]:
x=np.multiply(b,b)

In [34]:
x

array([[ 2.25,  4.  ,  9.  ],
       [16.  , 25.  , 36.  ]])

In [35]:
np.divide(b,b)

array([[1., 1., 1.],
       [1., 1., 1.]])

In [36]:
np.add(a,b)

array([[2.5, 4. , 6. ],
       [5. , 7. , 9. ]])

In [37]:
np.subtract(a,b)

array([[-0.5,  0. ,  0. ],
       [-3. , -3. , -3. ]])

In [38]:
np.sqrt(a)

array([1.        , 1.41421356, 1.73205081])

In [39]:
np.sqrt(b)

array([[1.22474487, 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [40]:
np.sqrt(c)

array([[[1.22474487, 1.41421356, 1.73205081],
        [2.        , 2.23606798, 2.44948974]],

       [[1.73205081, 1.41421356, 1.        ],
        [2.        , 2.23606798, 2.44948974]]])

In [41]:
np.add(a,b)

array([[2.5, 4. , 6. ],
       [5. , 7. , 9. ]])

In [42]:
np.min(a)

np.int32(1)

In [43]:
np.max(a)

np.int32(3)

In [44]:
np.cumsum(a)

array([1, 3, 6])

In [45]:
np.mean(a)

np.float64(2.0)

In [46]:
np.median(a)

np.float64(2.0)